Sprint_9
Elena2208/java-filmorate pull request #1
Opened 2022-11-03 19:10 UTC by Elena2208

2022-11-03 21:34 UTC, Elena2208 commented
Созданы классы Film,User. Разработаны контроллеры

2022-11-04 11:50 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе. Жду новую версию

2022-11-04 11:50 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Lombok есть в spring-boot-starter-parent версию можно не указывать

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Лишняя пустая строчка

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(Film.class);
Можно использовать аннотацию Slf4j. Это во первых, во вторых, у Вас в классе логгера указал класс Film. Нужно ставить тот класс который логгирует, т.е. FilmController

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Лишняя пустая строчка

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Updated the movie object.");
Съехало форматирование

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film newFilm = Film.builder().id(film.getId()).name(film.getName()).description(film.getDescription())
А зачем в контроллере новый обьект создавать? Передавайте сразу в сервис этот обьект и дальше с ним работайте.
Вообще по идее слой контроллера отвечает только за валидацию, а дальнейшая логика должна быть в сервисе

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User newUser= User.builder().id(user.getId()).email(user.getEmail()).login(user.getLogin())
Обычно, когда билдер используют принято в такой манере создавать переменную:
User.builder
.id
.name
.email
...
.build

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Зачем Вы лишние пустые строчки оставляете в начале и конце класса? Это бросается в глаза...

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@With
А для чего используется? Не видел использования раньше

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String description;
А почему у полей нет модификаторов приватных?

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film updateFilm(Film film) {
Между методами одну пустую строчку оставляйте

2022-11-04 11:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    {
Скобка должна быть после ()

2022-11-07 16:46 UTC, Frilock approved these changes
Принято

2022-11-08 20:06 UTC, merged